import { useMutation, useQuery } from '@tanstack/react-query'
import { FileCheck2, PackageCheck, Rocket, ShieldCheck, UploadCloud } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api } from '../api'
import { EmptyState, ErrorState, formatTime, LoadingState, PageTitle, Panel, StatusPill } from '../components/UI'

interface Release { id: string; version: string; channel: string; hardware_target: string; protocol_min: string; protocol_max: string; size_bytes: number; sha256: string; signing_key_id: string; release_notes: string; verified_at: string; active: boolean }
interface Deployment { id: string; firmware_release_id: string; device_id: string; status: string; scheduled_at: string; downloaded_at?: string; installed_at?: string; validated_at?: string; failure_reason?: string; rollback_at?: string }

export function FirmwarePage() {
  const [manifest, setManifest] = useState<File>()
  const [binary, setBinary] = useState<File>()
  const [publicKey, setPublicKey] = useState('')
  const releases = useQuery({ queryKey: ['firmware'], queryFn: () => api<Release[]>('/api/v1/firmware-releases') })
  const deployments = useQuery({ queryKey: ['deployments'], queryFn: () => api<Deployment[]>('/api/v1/firmware-deployments') })
  const upload = useMutation({ mutationFn: async () => { if (!manifest || !binary) throw new Error('Manifest and binary are required'); const form = new FormData(); form.append('manifest_json', await manifest.text()); form.append('public_key_pem', publicKey); form.append('binary', binary); return api('/api/v1/firmware-releases', { method: 'POST', body: form }) }, onSuccess: () => void releases.refetch() })
  const submit = (event: FormEvent) => { event.preventDefault(); upload.mutate() }
  return (
    <>
      <PageTitle eyebrow="Signed OTA" title="Firmware management" description="Upload pre-signed packages, verify them before activation, target compatible hardware, and observe download through rollback." />
      <div className="firmware-grid"><Panel title="Upload verified release" eyebrow="Private key stays offline"><form className="stack-form" onSubmit={submit}><label className="file-drop"><UploadCloud /><span><strong>Signed manifest</strong><small>{manifest?.name ?? 'Choose JSON manifest'}</small></span><input type="file" accept="application/json,.json" onChange={(event) => { setManifest(event.target.files?.[0]); }} required /></label><label className="file-drop"><PackageCheck /><span><strong>Firmware binary</strong><small>{binary?.name ?? 'Choose .bin package'}</small></span><input type="file" accept=".bin,application/octet-stream" onChange={(event) => { setBinary(event.target.files?.[0]); }} required /></label><label><span>Ed25519 public key (PEM)</span><textarea rows={5} value={publicKey} onChange={(event) => { setPublicKey(event.target.value); }} placeholder="-----BEGIN PUBLIC KEY-----" required /></label><button className="button primary" disabled={upload.isPending}><FileCheck2 size={17} /> Verify and store</button>{upload.error && <p className="field-error">{upload.error.message}</p>}</form></Panel><Panel title="Release safeguards" eyebrow="Before activation"><div className="safeguard-list"><div><ShieldCheck /><p><strong>Signature and hash</strong><small>Both are verified before bytes enter a deployment ring.</small></p></div><div><Rocket /><p><strong>Compatibility gate</strong><small>Hardware target and protocol range must match every device.</small></p></div><div><PackageCheck /><p><strong>Explicit deployment</strong><small>Development, canary, and stable rings never deploy automatically.</small></p></div></div></Panel></div>
      <Panel title="Release library" eyebrow="Server-verified packages">{releases.isLoading ? <LoadingState /> : releases.error ? <ErrorState error={releases.error} /> : releases.data?.length ? <div className="release-list">{releases.data.map((release) => <article key={release.id}><span className="release-version">v{release.version}</span><div><strong>{release.hardware_target}</strong><small>{release.release_notes}</small><code title={release.sha256}>{release.sha256.slice(0, 18)}…</code></div><dl><div><dt>Channel</dt><dd>{release.channel}</dd></div><div><dt>Protocol</dt><dd>{release.protocol_min}</dd></div><div><dt>Verified</dt><dd>{formatTime(release.verified_at)}</dd></div></dl><StatusPill status={release.active ? 'healthy' : 'pending'} label={release.active ? 'Active' : 'Stored'} /></article>)}</div> : <EmptyState title="No firmware packages" message="Upload a pre-signed compatible manifest and binary to begin." />}</Panel>
      <Panel title="Deployment state" eyebrow="Scheduled → downloaded → installed → validated">{deployments.data?.length ? <div className="responsive-table"><table><thead><tr><th>Device</th><th>Release</th><th>Scheduled</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{deployments.data.map((deployment) => <tr key={deployment.id}><td>{deployment.device_id.slice(0, 8)}…</td><td>{deployment.firmware_release_id.slice(0, 8)}…</td><td>{formatTime(deployment.scheduled_at)}</td><td><StatusPill status={deployment.status} /></td><td>{deployment.failure_reason ?? (deployment.validated_at ? `Validated ${formatTime(deployment.validated_at)}` : 'Awaiting next report')}</td></tr>)}</tbody></table></div> : <EmptyState title="No deployments" message="Activate a compatible signed release and assign devices explicitly." />}</Panel>
    </>
  )
}

